
########################################  Running CUTe test(s)  ########################################

check_sint_suite::check_sint_literal_equal_fail_test .............................................. fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:17
caller: check_sint_literal_equal_fail_test__cute_exec()
wanted: 0 == 1
found:  [0] != [1]

check_sint_suite::check_sint_var_equal_fail_test .................................................. fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:24
caller: check_sint_var_equal_fail_test__cute_exec()
wanted: chk == -1
found:  [2] != [-1]

check_sint_suite::check_sint_equal_ref_fail_test .................................................. fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:31
caller: check_sint_equal_ref_fail_test__cute_exec()
wanted: -1 == ref
found:  [-1] != [2]

check_sint_suite::check_sint_var_equal_ref_fail_test .............................................. fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:39
caller: check_sint_var_equal_ref_fail_test__cute_exec()
wanted: chk == ref
found:  [2] != [3]

check_sint_suite::check_sint_literal_unequal_fail_test ............................................ fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:56
caller: check_sint_literal_unequal_fail_test__cute_exec()
wanted: 1 != 1
found:  [1] == [1]

check_sint_suite::check_sint_var_unequal_fail_test ................................................ fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:63
caller: check_sint_var_unequal_fail_test__cute_exec()
wanted: chk != 2
found:  [2] == [2]

check_sint_suite::check_sint_unequal_ref_fail_test ................................................ fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:70
caller: check_sint_unequal_ref_fail_test__cute_exec()
wanted: 2 != ref
found:  [2] == [2]

check_sint_suite::check_sint_var_unequal_ref_fail_test ............................................ fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:78
caller: check_sint_var_unequal_ref_fail_test__cute_exec()
wanted: chk != ref
found:  [2] == [2]

check_sint_suite::check_sint_literal_greater_fail_test ............................................ fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:94
caller: check_sint_literal_greater_fail_test__cute_exec()
wanted: 1 > 1
found:  [1] <= [1]

check_sint_suite::check_sint_var_greater_fail_test ................................................ fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:101
caller: check_sint_var_greater_fail_test__cute_exec()
wanted: chk > 1
found:  [-1] <= [1]

check_sint_suite::check_sint_greater_ref_fail_test ................................................ fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:108
caller: check_sint_greater_ref_fail_test__cute_exec()
wanted: -1 > ref
found:  [-1] <= [1]

check_sint_suite::check_sint_var_greater_ref_fail_test ............................................ fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:116
caller: check_sint_var_greater_ref_fail_test__cute_exec()
wanted: chk > ref
found:  [-1] <= [-1]

check_sint_suite::check_sint_literal_greater_equal_fail_test ...................................... fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:135
caller: check_sint_literal_greater_equal_fail_test__cute_exec()
wanted: 0 >= 1
found:  [0] < [1]

check_sint_suite::check_sint_var_greater_equal_fail_test .......................................... fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:142
caller: check_sint_var_greater_equal_fail_test__cute_exec()
wanted: chk >= 1
found:  [-1] < [1]

check_sint_suite::check_sint_greater_equal_ref_fail_test .......................................... fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:149
caller: check_sint_greater_equal_ref_fail_test__cute_exec()
wanted: -1 >= ref
found:  [-1] < [1]

check_sint_suite::check_sint_var_greater_equal_ref_fail_test ...................................... fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:157
caller: check_sint_var_greater_equal_ref_fail_test__cute_exec()
wanted: chk >= ref
found:  [-1] < [0]

check_sint_suite::check_sint_literal_lower_fail_test .............................................. fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:173
caller: check_sint_literal_lower_fail_test__cute_exec()
wanted: 0 < 0
found:  [0] >= [0]

check_sint_suite::check_sint_var_lower_fail_test .................................................. fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:180
caller: check_sint_var_lower_fail_test__cute_exec()
wanted: chk < -1
found:  [1] >= [-1]

check_sint_suite::check_sint_lower_ref_fail_test .................................................. fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:187
caller: check_sint_lower_ref_fail_test__cute_exec()
wanted: -1 < ref
found:  [-1] >= [-1]

check_sint_suite::check_sint_var_lower_ref_fail_test .............................................. fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:195
caller: check_sint_var_lower_ref_fail_test__cute_exec()
wanted: chk < ref
found:  [0] >= [-1]

check_sint_suite::check_sint_literal_lower_equal_fail_test ........................................ fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:214
caller: check_sint_literal_lower_equal_fail_test__cute_exec()
wanted: 1 <= 0
found:  [1] > [0]

check_sint_suite::check_sint_var_lower_equal_fail_test ............................................ fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:221
caller: check_sint_var_lower_equal_fail_test__cute_exec()
wanted: chk <= -1
found:  [1] > [-1]

check_sint_suite::check_sint_lower_equal_ref_fail_test ............................................ fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:228
caller: check_sint_lower_equal_ref_fail_test__cute_exec()
wanted: 0 <= ref
found:  [0] > [-1]

check_sint_suite::check_sint_var_lower_equal_ref_fail_test ........................................ fail
issue:  exec failed
reason: signed integer value check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:236
caller: check_sint_var_lower_equal_ref_fail_test__cute_exec()
wanted: chk <= ref
found:  [0] > [-1]

check_sint_suite::check_sint_literal_in_range_fail_test ........................................... fail
issue:  exec failed
reason: signed integer range check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:256
caller: check_sint_literal_in_range_fail_test__cute_exec()
wanted: 0 in range {1 ... 10}
found:  [0] not in range {1 ... 10}

check_sint_suite::check_sint_var_in_range_fail_test ............................................... fail
issue:  exec failed
reason: signed integer range check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:263
caller: check_sint_var_in_range_fail_test__cute_exec()
wanted: chk in range {1 ... 10}
found:  [11] not in range {1 ... 10}

check_sint_suite::check_sint_in_range_ref_fail_test ............................................... fail
issue:  exec failed
reason: signed integer range check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:272
caller: check_sint_in_range_ref_fail_test__cute_exec()
wanted: 0 in range {min_ref ... max_ref}
found:  [0] not in range {5 ... 5}

check_sint_suite::check_sint_var_in_range_ref_fail_test ........................................... fail
issue:  exec failed
reason: signed integer range check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:283
caller: check_sint_var_in_range_ref_fail_test__cute_exec()
wanted: chk in range {min_ref ... max_ref}
found:  [6] not in range {5 ... 5}

check_sint_suite::check_sint_literal_not_in_range_fail_test ....................................... fail
issue:  exec failed
reason: signed integer range check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:303
caller: check_sint_literal_not_in_range_fail_test__cute_exec()
wanted: 1 not in range {1 ... 10}
found:  [1] in range {1 ... 10}

check_sint_suite::check_sint_var_not_in_range_fail_test ........................................... fail
issue:  exec failed
reason: signed integer range check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:309
caller: check_sint_var_not_in_range_fail_test__cute_exec()
wanted: chk not in range {1 ... 10}
found:  [10] in range {1 ... 10}

check_sint_suite::check_sint_not_in_range_ref_fail_test ........................................... fail
issue:  exec failed
reason: signed integer range check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:318
caller: check_sint_not_in_range_ref_fail_test__cute_exec()
wanted: 5 not in range {min_ref ... max_ref}
found:  [5] in range {1 ... 10}

check_sint_suite::check_sint_var_not_in_range_ref_fail_test ....................................... fail
issue:  exec failed
reason: signed integer range check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:329
caller: check_sint_var_not_in_range_ref_fail_test__cute_exec()
wanted: chk not in range {min_ref ... max_ref}
found:  [5] in range {5 ... 5}

check_sint_suite::check_sint_literal_in_set_fail_test ............................................. fail
issue:  exec failed
reason: signed integer set check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:349
caller: check_sint_literal_in_set_fail_test__cute_exec()
wanted: -1 in set {0, 1, 2, 3, 5, 8}
found:  [-1] not in set {0, 1, 2, 3, 5, 8}

check_sint_suite::check_sint_var_in_set_fail_test ................................................. fail
issue:  exec failed
reason: signed integer set check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:356
caller: check_sint_var_in_set_fail_test__cute_exec()
wanted: chk in set {0, 1, 2, 3, 5, 8}
found:  [4] not in set {0, 1, 2, 3, 5, 8}

check_sint_suite::check_sint_in_set_ref_fail_test ................................................. fail
issue:  exec failed
reason: signed integer set check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:366
caller: check_sint_in_set_ref_fail_test__cute_exec()
wanted: 4 in set {ref0, 1, 2, 3, ref5, 8}
found:  [4] not in set {0, 1, 2, 3, 5, 8}

check_sint_suite::check_sint_var_in_set_ref_fail_test ............................................. fail
issue:  exec failed
reason: signed integer set check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:378
caller: check_sint_var_in_set_ref_fail_test__cute_exec()
wanted: chk in set {ref0, 1, 2, 3, ref5, 8}
found:  [10] not in set {0, 1, 2, 3, 5, 8}

check_sint_suite::check_sint_literal_not_in_set_fail_test ......................................... fail
issue:  exec failed
reason: signed integer set check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:398
caller: check_sint_literal_not_in_set_fail_test__cute_exec()
wanted: 1 not in set {0, 1, 2, 3, 5, 8}
found:  [1] in set {0, 1, 2, 3, 5, 8}

check_sint_suite::check_sint_var_not_in_set_fail_test ............................................. fail
issue:  exec failed
reason: signed integer set check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:405
caller: check_sint_var_not_in_set_fail_test__cute_exec()
wanted: chk not in set {0, 1, 2, 3, 5, 8}
found:  [8] in set {0, 1, 2, 3, 5, 8}

check_sint_suite::check_sint_not_in_set_ref_fail_test ............................................. fail
issue:  exec failed
reason: signed integer set check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:415
caller: check_sint_not_in_set_ref_fail_test__cute_exec()
wanted: 0 not in set {ref0, 1, 2, 3, ref5, 8}
found:  [0] in set {0, 1, 2, 3, 5, 8}

check_sint_suite::check_sint_var_not_in_set_ref_fail_test ......................................... fail
issue:  exec failed
reason: signed integer set check failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:427
caller: check_sint_var_not_in_set_ref_fail_test__cute_exec()
wanted: chk not in set {ref0, 1, 2, 3, ref5, 8}
found:  [5] in set {0, 1, 2, 3, 5, 8}

check_sint_suite .................................................................................. fail
issue:  exec failed
reason: descendants failed
source: /mnt/devel/greg/tidor/cute/test/check_sint.c:492

NAME                                          STAT  TIME(s.us)  #PASS  #SKIP  #FAIL  #EXCP  #EXEC #TOTAL
check_sint_suite                              fail    0.933136     10      0     40      0     50     50
                                                                  20%     0%    80%     0%   100%
--------------------------------------------------------------------------------------------------------
Total                                         fail    0.933136     10      0     40      0     50     50
                                                                  20%     0%    80%     0%   100%

                                  ###           SUMMARY            ###
                                  ###  40/50 (80%) test(s) FAILED  ###

